# The URL the site will be built for
base_url = "https://thatarcticpenguin.is-a.dev/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "That Arctic Penguin"
description = "Developer, ice cream enthusiast, and penguin lover. This is the personal site of Sabareesh Vinodh."
default_language = "en"
generate_feeds = true
feed_filenames = ["rss.xml"]
taxonomies = [
    { name = "tags", feed = true }
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here

[search]
include_title = true
include_description = false
include_date = false
include_path = false
include_content = true
truncate_content_length = 500
index_format = "elasticlunr_javascript"
